"""Experiment AZ: physical-boundary ambiguity versus robust downstream evidence."""
from __future__ import annotations

import json
from pathlib import Path

from observer_math.robust_boundary_evidence import evidence_path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "boundary_ambiguity_to_robust_evidence_audit.json"


def main() -> None:
    e_values = {"W0": 30.0, "W1": 2.0, "W2": 8.0, "W3": 25.0}
    stages = {
        "broad_boundary_set": ("W0", "W1", "W2", "W3"),
        "certified_compression": ("W0", "W1"),
        "boundary_resolved": ("W0",),
    }
    points = evidence_path(stages, e_values, selected_path="W0", threshold=20.0)
    record = {
        "experiment": "AZ",
        "title": "Boundary ambiguity to robust downstream evidence",
        "threshold": 20.0,
        "path_specific_e_values": e_values,
        "points": [
            {
                "stage": p.stage,
                "retained_paths": list(p.retained_paths),
                "selected_e_value": p.selected_e_value,
                "robust_e_value": p.robust_e_value,
                "crosses_threshold": p.crosses_threshold,
            }
            for p in points
        ],
        "negative_control": {
            "statement": "Strong selected-path evidence is deliberately insufficient while a weak-evidence physical competitor remains admissible.",
            "selected_path_e_value": 30.0,
            "blocking_competitor_e_value": 2.0,
        },
        "scientific_boundary": "Values are controlled downstream e-values used to audit the P62/P66 envelope. This experiment does not claim they were generated by a biological or experiential measurement.",
    }
    OUTPUT.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(record, indent=2))


if __name__ == "__main__":
    main()
