"""Experiment AX: measurement precision versus boundary ambiguity and workload."""
from __future__ import annotations

import json
from pathlib import Path

from observer_math.precision_workload import precision_workload_curve

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "precision_ambiguity_workload_audit.json"


def main() -> None:
    actions = {"W0": 1.254324, "W1": 1.127903, "W2": 1.04, "W3": 0.91, "W4": 0.72, "W5": 0.55}
    radii = {"W0": 0.16, "W1": 0.17, "W2": 0.18, "W3": 0.19, "W4": 0.20, "W5": 0.21}
    scales = (2.0, 1.5, 1.0, 0.75, 0.5, 0.25, 0.1, 0.0)
    points = precision_workload_curve(actions, radii, scales)
    record = {
        "experiment": "AX",
        "purpose": "controlled diagnostic of how certified uncertainty width changes the number of physical paths requiring downstream evaluation",
        "nominal_actions": actions,
        "base_action_radii": radii,
        "points": [
            {
                "precision_scale": p.precision_scale,
                "retained_count": p.retained_count,
                "pruned_count": p.pruned_count,
                "compression_fraction": p.compression_fraction,
                "retained_paths": list(p.retained_paths),
            }
            for p in points
        ],
        "scientific_boundary": "The radii are controlled action-level inputs. This experiment demonstrates the P64-to-P63 engineering response and does not claim these scales are generated by a particular sensor or sample count.",
    }
    OUTPUT.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(record, indent=2))


if __name__ == "__main__":
    main()
