"""Mathematical tools for detecting spatiotemporal observer-like subsystems."""

from .baselines import BaselinePath, best_fixed_boundary, independent_local_path
from .identifiability import (
    TwoPointIdentifiabilityBound,
    canonical_path_orbit,
    paths_equivalent_under_permutations,
    two_point_identifiability_bound,
)
from .metrics import ObserverMetrics, observer_metrics, observer_metrics_from_covariances
from .models import (
    block_system,
    correlated_but_uncoupled_system,
    covariance_preserving_moving_cliques,
    moving_module_systems,
    perturbed_covariance_preserving_moving_cliques,
    ring_system,
)
from .nonstationary import (
    TransportMetrics,
    adjacent_joint_covariance,
    propagate_covariances,
    transport_metrics,
    transport_metrics_from_covariances,
)
from .recovery import (
    ComponentwiseRecoveryBound,
    FiniteSampleRecoveryBound,
    GaussianPathRecoveryBound,
    LocalizedGaussianPathRecoveryBound,
    NearCompetitorScreen,
    canonical_persistence_covariance_error_bound,
    componentwise_recovery_bound,
    finite_sample_recovery_bound,
    gaussian_cmi_covariance_error_bound,
    gaussian_path_recovery_bound,
    linear_gaussian_localized_recovery_bound,
    localized_gaussian_path_recovery_bound,
    minimum_gaussian_sample_size,
    minimum_localized_gaussian_sample_size,
    product_root_error_bound,
    screen_near_competitors,
)
from .sampling import (
    adjacent_sample_covariances,
    regularized_sample_covariance,
    simulate_gaussian_ensemble,
)
from .search import Candidate, rank_subsystems
from .symbolic import (
    APrioriSupportMovingCliqueRecoveryBound,
    MovingCliqueRecoveryBound,
    PerturbedMovingCliqueRecoveryBound,
    SupportResolvedMovingCliqueRecoveryBound,
    a_priori_support_moving_clique_recovery_bound,
    covariance_preserving_moving_clique_bound,
    perturbed_moving_clique_recovery_bound,
    support_resolved_moving_clique_recovery_bound,
)
from .worldtube import (
    WorldTubeCertificate,
    WorldTubeResult,
    certify_worldtube,
    optimize_worldtube,
    structural_transport,
)

__all__ = [
    "APrioriSupportMovingCliqueRecoveryBound",
    "BaselinePath",
    "Candidate",
    "ComponentwiseRecoveryBound",
    "FiniteSampleRecoveryBound",
    "GaussianPathRecoveryBound",
    "LocalizedGaussianPathRecoveryBound",
    "MovingCliqueRecoveryBound",
    "NearCompetitorScreen",
    "ObserverMetrics",
    "PerturbedMovingCliqueRecoveryBound",
    "SupportResolvedMovingCliqueRecoveryBound",
    "TransportMetrics",
    "TwoPointIdentifiabilityBound",
    "WorldTubeCertificate",
    "WorldTubeResult",
    "a_priori_support_moving_clique_recovery_bound",
    "adjacent_joint_covariance",
    "adjacent_sample_covariances",
    "best_fixed_boundary",
    "block_system",
    "canonical_path_orbit",
    "canonical_persistence_covariance_error_bound",
    "certify_worldtube",
    "componentwise_recovery_bound",
    "correlated_but_uncoupled_system",
    "covariance_preserving_moving_clique_bound",
    "covariance_preserving_moving_cliques",
    "finite_sample_recovery_bound",
    "gaussian_cmi_covariance_error_bound",
    "gaussian_path_recovery_bound",
    "independent_local_path",
    "linear_gaussian_localized_recovery_bound",
    "localized_gaussian_path_recovery_bound",
    "minimum_gaussian_sample_size",
    "minimum_localized_gaussian_sample_size",
    "moving_module_systems",
    "observer_metrics",
    "observer_metrics_from_covariances",
    "optimize_worldtube",
    "paths_equivalent_under_permutations",
    "perturbed_covariance_preserving_moving_cliques",
    "perturbed_moving_clique_recovery_bound",
    "product_root_error_bound",
    "propagate_covariances",
    "rank_subsystems",
    "regularized_sample_covariance",
    "ring_system",
    "screen_near_competitors",
    "simulate_gaussian_ensemble",
    "structural_transport",
    "support_resolved_moving_clique_recovery_bound",
    "transport_metrics",
    "transport_metrics_from_covariances",
    "two_point_identifiability_bound",
]
