"""Sampling-consistent exponential relaxation geometry.

Proposition 53 replaces the sample-index AR(1) coefficient by a physical
relaxation time whenever an exponential covariance model is appropriate. The
same relaxation time generates consistent covariance matrices on uniform,
coarse, and irregular sampling grids.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import ArrayLike

from .compact_temporal_family import (
    GaussianCompactTemporalFamilyMatrixChernoffBound,
    gaussian_compact_temporal_family_matrix_chernoff_bound,
)


@dataclass(frozen=True)
class ExponentialRelaxationTemporalCover:
    """Finite cover of a physical exponential-relaxation covariance family."""

    sample_times: np.ndarray
    relaxation_time_grid: np.ndarray
    temporal_covariance_grid: np.ndarray
    relaxation_time_lower_bound: float
    relaxation_time_upper_bound: float
    maximum_relaxation_time_spacing: float
    operator_lipschitz_bound: float
    raw_operator_covering_radius: float
    projected_eigenvalue_covering_radius: float
    projected_normalization_covering_radius: float
    nuisance_rank: int


@dataclass(frozen=True)
class GaussianRelaxationTimeMatrixChernoffBound:
    """Proposition 49 covariance certificate parameterized by relaxation time."""

    temporal_cover: ExponentialRelaxationTemporalCover
    covariance_bound: GaussianCompactTemporalFamilyMatrixChernoffBound


def _validated_positive(value: float, name: str) -> float:
    number = float(value)
    if not np.isfinite(number) or number <= 0.0:
        raise ValueError(f"{name} must be finite and positive")
    return number


def _validated_sample_times(sample_times: ArrayLike) -> np.ndarray:
    times = np.asarray(sample_times, dtype=float)
    if times.ndim != 1 or times.size < 2:
        raise ValueError("sample_times must be a one-dimensional array with at least two entries")
    if not np.all(np.isfinite(times)):
        raise ValueError("sample_times must be finite")
    if not np.all(np.diff(times) > 0.0):
        raise ValueError("sample_times must be strictly increasing")
    return times


def relaxation_autocorrelation(sample_interval: float, relaxation_time: float) -> float:
    """Return the one-step correlation generated by an exponential relaxation time."""
    interval = _validated_positive(sample_interval, "sample_interval")
    tau = _validated_positive(relaxation_time, "relaxation_time")
    return float(np.exp(-interval / tau))


def relaxation_time_from_autocorrelation(
    autocorrelation: float,
    sample_interval: float,
) -> float:
    """Recover physical relaxation time from a uniform-sampling AR(1) coefficient."""
    phi = float(autocorrelation)
    interval = _validated_positive(sample_interval, "sample_interval")
    if not np.isfinite(phi) or not 0.0 < phi < 1.0:
        raise ValueError("autocorrelation must lie strictly between zero and one")
    return float(-interval / np.log(phi))


def exponential_relaxation_covariance(
    sample_times: ArrayLike,
    relaxation_time: float,
) -> np.ndarray:
    """Return K_ij = exp(-|t_i-t_j|/tau) on any strictly increasing time grid."""
    times = _validated_sample_times(sample_times)
    tau = _validated_positive(relaxation_time, "relaxation_time")
    distances = np.abs(times[:, None] - times[None, :])
    return np.exp(-distances / tau)


def uniform_exponential_relaxation_covariance(
    sample_count: int,
    sample_interval: float,
    relaxation_time: float,
) -> np.ndarray:
    """Return the uniform-grid covariance associated with one physical relaxation time."""
    if isinstance(sample_count, bool) or not isinstance(sample_count, (int, np.integer)):
        raise TypeError("sample_count must be an integer")
    if sample_count < 2:
        raise ValueError("sample_count must be at least two")
    interval = _validated_positive(sample_interval, "sample_interval")
    times = interval * np.arange(sample_count, dtype=float)
    return exponential_relaxation_covariance(times, relaxation_time)


def _entrywise_relaxation_derivative_supremum(
    distance: float,
    lower_relaxation_time: float,
    upper_relaxation_time: float,
) -> float:
    if distance <= 0.0:
        return 0.0
    candidate = float(
        np.clip(
            0.5 * distance,
            lower_relaxation_time,
            upper_relaxation_time,
        )
    )
    return float(distance * np.exp(-distance / candidate) / candidate**2)


def exponential_relaxation_operator_lipschitz_bound(
    sample_times: ArrayLike,
    lower_relaxation_time: float,
    upper_relaxation_time: float,
) -> float:
    """Bound ||K_tau-K_tau'||_2 by L |tau-tau'| over a relaxation-time interval.

    For d=|t_i-t_j|, the derivative magnitude is

        d exp(-d/tau) / tau^2.

    For d>0 its unconstrained maximum occurs at tau=d/2. Clipping d/2 to
    the declared relaxation-time interval therefore gives the exact scalar
    supremum for each matrix entry. The maximum absolute row sum of those
    entrywise suprema bounds the matrix operator norm uniformly.
    """
    times = _validated_sample_times(sample_times)
    lower = _validated_positive(lower_relaxation_time, "lower_relaxation_time")
    upper = _validated_positive(upper_relaxation_time, "upper_relaxation_time")
    if upper < lower:
        raise ValueError("upper_relaxation_time must be at least lower_relaxation_time")

    distances = np.abs(times[:, None] - times[None, :])
    derivative_suprema = np.zeros_like(distances)
    for i in range(times.size):
        for j in range(times.size):
            derivative_suprema[i, j] = _entrywise_relaxation_derivative_supremum(
                float(distances[i, j]),
                lower,
                upper,
            )
    return float(np.max(np.sum(derivative_suprema, axis=1)))


def exponential_relaxation_temporal_cover(
    sample_times: ArrayLike,
    nuisance_design: ArrayLike,
    *,
    lower_relaxation_time: float,
    upper_relaxation_time: float,
    relaxation_time_grid_size: int = 33,
) -> ExponentialRelaxationTemporalCover:
    """Build a certified finite cover of an exponential relaxation-time family."""
    times = _validated_sample_times(sample_times)
    lower = _validated_positive(lower_relaxation_time, "lower_relaxation_time")
    upper = _validated_positive(upper_relaxation_time, "upper_relaxation_time")
    if upper < lower:
        raise ValueError("upper_relaxation_time must be at least lower_relaxation_time")
    if isinstance(relaxation_time_grid_size, bool) or not isinstance(
        relaxation_time_grid_size, (int, np.integer)
    ):
        raise TypeError("relaxation_time_grid_size must be an integer")
    if relaxation_time_grid_size < 2:
        raise ValueError("relaxation_time_grid_size must be at least two")

    design = np.asarray(nuisance_design, dtype=float)
    if design.ndim != 2 or design.shape[0] != times.size:
        raise ValueError("nuisance_design must have one row per sample time")
    if design.shape[1] < 1 or design.shape[1] >= times.size:
        raise ValueError("nuisance_design must have rank between one and sample_count-1")
    if not np.all(np.isfinite(design)):
        raise ValueError("nuisance_design must be finite")
    if np.linalg.matrix_rank(design) != design.shape[1]:
        raise ValueError("nuisance_design must have full column rank")

    tau_grid = np.linspace(lower, upper, relaxation_time_grid_size)
    temporal_grid = np.stack(
        [exponential_relaxation_covariance(times, tau) for tau in tau_grid]
    )
    maximum_spacing = float(np.max(np.diff(tau_grid)))
    lipschitz = exponential_relaxation_operator_lipschitz_bound(times, lower, upper)
    raw_radius = float(0.5 * maximum_spacing * lipschitz)

    nuisance_rank = int(design.shape[1])
    return ExponentialRelaxationTemporalCover(
        sample_times=times.copy(),
        relaxation_time_grid=tau_grid,
        temporal_covariance_grid=temporal_grid,
        relaxation_time_lower_bound=lower,
        relaxation_time_upper_bound=upper,
        maximum_relaxation_time_spacing=maximum_spacing,
        operator_lipschitz_bound=lipschitz,
        raw_operator_covering_radius=raw_radius,
        projected_eigenvalue_covering_radius=raw_radius,
        projected_normalization_covering_radius=float(nuisance_rank * raw_radius),
        nuisance_rank=nuisance_rank,
    )


def gaussian_relaxation_time_matrix_chernoff_bound(
    sample_times: ArrayLike,
    nuisance_design: ArrayLike,
    block_dimension: int,
    block_count: int,
    *,
    lower_relaxation_time: float,
    upper_relaxation_time: float,
    relaxation_time_grid_size: int = 33,
    confidence: float = 0.975,
    upper_theta_grid_size: int = 4096,
    lower_theta_grid_size: int = 4096,
) -> GaussianRelaxationTimeMatrixChernoffBound:
    """Certify target covariance over a physical relaxation-time interval."""
    cover = exponential_relaxation_temporal_cover(
        sample_times,
        nuisance_design,
        lower_relaxation_time=lower_relaxation_time,
        upper_relaxation_time=upper_relaxation_time,
        relaxation_time_grid_size=relaxation_time_grid_size,
    )
    covariance_bound = gaussian_compact_temporal_family_matrix_chernoff_bound(
        block_dimension=block_dimension,
        block_count=block_count,
        temporal_covariance_grid=cover.temporal_covariance_grid,
        nuisance_design=nuisance_design,
        eigenvalue_covering_radius=cover.projected_eigenvalue_covering_radius,
        normalization_covering_radius=cover.projected_normalization_covering_radius,
        confidence=confidence,
        upper_theta_grid_size=upper_theta_grid_size,
        lower_theta_grid_size=lower_theta_grid_size,
    )
    return GaussianRelaxationTimeMatrixChernoffBound(
        temporal_cover=cover,
        covariance_bound=covariance_bound,
    )
